namespace: cisco
name: sdwan_deployment
version: 0.3.2
readme: README.md
authors:
  - Arkadiusz Cichon <acichon@cisco.com>
description: Ansible collection to deploy Cisco SD-WAN on AWS and Azure

repository: https://github.com/cisco-open/ansible-collection-sdwan-deployment
documentation: https://github.com/cisco-open/ansible-collection-sdwan-deployment/blob/main/README.md
homepage: https://github.com/cisco-open/ansible-collection-sdwan-deployment
issues: https://github.com/cisco-open/ansible-collection-sdwan-deployment/issues

license:
  - "GPL-3.0-only"

tags:
  - cisco
  - sdwan
  - catalystwan
  - networking

dependencies: {}
build_ignore: []
