# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

- name: Remove VPC
  amazon.aws.ec2_vpc_net:
    state: absent
    name: "{{ aws_vpc_name }}"
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_region }}"
