# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

- name: Ask user for confirmation to teardown resources
  ansible.builtin.pause:
    prompt: Do you want to continue? (yes/no) [yes]
  register: user_response

- name: Stop teardown if user response is 'no'
  ansible.builtin.meta: end_play
  when: user_response.user_input | default('yes') | lower == 'no'

- name: Verify if user session with AWS is active
  ansible.builtin.include_role:
    name: common
    tasks_from: aws_user_session_probe

# VPC info
- name: Retrieve VPC details  # noqa: syntax-check[unknown-module]
  amazon.aws.ec2_vpc_net_info:  # noqa: syntax-check[unknown-module]
    region: "{{ _region }}"
    filters:
      "tag:Name": "{{ aws_vpc_name }}"
      "tag:Creator": "{{ aws_tag_creator }}"
  register: vpc_info
  loop: "{{ all_aws_regions }}"
  loop_control:
    label: "{{ _region }}"
    loop_var: _region

- name: Check if VPC info is not empty
  ansible.builtin.assert:
    that:
      - vpc_info.results | map(attribute='vpcs') | flatten | length > 0
    fail_msg: "No VPC found. Please check your VPC configuration. Might be that you already removed your configuration."

- name: Set fact from register variable
  ansible.builtin.set_fact:
    aws_vpc_region: "{{ aws_vpc_region | default([]) + [{'vpc_id': _vpc.vpcs[0].id, 'region': _vpc._region}] }}"
  loop:
    "{{ vpc_info.results }}"
  when: _vpc.vpcs
  loop_control:
    label: "{{ _vpc._region }}"
    loop_var: _vpc

#######################    Teardown    #######################

- name: Stop and terminate specific ec2 instances and their NICs and EIPs
  ansible.builtin.include_tasks: ec2_specific_instance.yml
  when: teardown_specific_instances

# ec2 instance
- name: Stop and terminate ec2 instance
  ansible.builtin.include_tasks: ec2_instance.yml
  when: not teardown_specific_instances
  loop: "{{ aws_vpc_region }}"
  loop_control:
    label: "{{ _vpc_region.region }}"
    loop_var: _vpc_region
  vars:
    aws_region: "{{ _vpc_region.region }}"
    aws_vpc_id: "{{ _vpc_region.vpc_id }}"

# eip and network interfaces
- name: Remove all network interfaces associated with VPC
  ansible.builtin.include_tasks: ec2_eni.yml
  when: not teardown_specific_instances
  loop: "{{ aws_vpc_region }}"
  loop_control:
    label: "{{ _vpc_region.region }}"
    loop_var: _vpc_region
  vars:
    aws_region: "{{ _vpc_region.region }}"
    aws_vpc_id: "{{ _vpc_region.vpc_id }}"

# security groups
- name: Remove all security groups associated with VPC
  when: not teardown_specific_instances
  ansible.builtin.include_tasks: ec2_group.yml
  loop: "{{ aws_vpc_region }}"
  loop_control:
    label: "{{ _vpc_region.region }}"
    loop_var: _vpc_region
  vars:
    aws_region: "{{ _vpc_region.region }}"
    aws_vpc_id: "{{ _vpc_region.vpc_id }}"

# route tables
- name: Remove all route tables associated with VPC
  when: not teardown_specific_instances
  ansible.builtin.include_tasks: ec2_vpc_route_table.yml
  loop: "{{ aws_vpc_region }}"
  loop_control:
    label: "{{ _vpc_region.region }}"
    loop_var: _vpc_region
  vars:
    aws_region: "{{ _vpc_region.region }}"
    aws_vpc_id: "{{ _vpc_region.vpc_id }}"

# subnets
- name: Remove all subnets associated with VPC
  when: not teardown_specific_instances
  ansible.builtin.include_tasks: ec2_vpc_subnet.yml
  loop: "{{ aws_vpc_region }}"
  loop_control:
    label: "{{ _vpc_region.region }}"
    loop_var: _vpc_region
  vars:
    aws_region: "{{ _vpc_region.region }}"
    aws_vpc_id: "{{ _vpc_region.vpc_id }}"

# igw
- name: Remove all internet gateways
  when: not teardown_specific_instances
  ansible.builtin.include_tasks: ec2_vpc_igw.yml
  loop: "{{ aws_vpc_region }}"
  loop_control:
    label: "{{ _vpc_region.region }}"
    loop_var: _vpc_region
  vars:
    aws_region: "{{ _vpc_region.region }}"
    aws_vpc_id: "{{ _vpc_region.vpc_id }}"

# vpc
- name: Remove VPC
  when: not teardown_specific_instances
  ansible.builtin.include_tasks: ec2_vpc_net.yml
  loop: "{{ aws_vpc_region }}"
  loop_control:
    label: "{{ _vpc_region.region }}"
    loop_var: _vpc_region
  vars:
    aws_region: "{{ _vpc_region.region }}"
    aws_vpc_id: "{{ _vpc_region.vpc_id }}"
