# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

- name: "Create resource group: {{ az_resource_group }}"
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ az_resource_group }}"
    location: "{{ az_location }}"
    tags:
      Name: "{{ az_resource_group }}"
      Creator: "{{ az_tag_creator }}"
      Organization: "{{ organization_name }}"

- name: "Create virtual network: {{ az_virtual_network }}"
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_virtual_network }}"
    address_prefixes: "{{ az_vn_address_prefixes_cidr }}"
    tags:
      Name: "{{ az_virtual_network }}"
      Creator: "{{ az_tag_creator }}"
      Organization: "{{ organization_name }}"

- name: "Create subnets inside virtual network: {{ az_virtual_network }}"
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ az_resource_group }}"
    name: "{{ subnet_item.name }}"
    address_prefixes_cidr: "{{ subnet_item.cidr }}"
    virtual_network: "{{ az_virtual_network }}"
  loop: "{{ az_subnets }}"
  loop_control:
    loop_var: subnet_item

# TODO enable for customers handy way to define not only az_allowed_subnets
# but also custom rules for Security Groups. Both AWS and Azure
- name: "Create Network Security Group: {{ az_network_security_group }}"
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_network_security_group }}"
    rules:
      - name: DenySSH
        protocol: Tcp
        destination_port_range: 22-23
        access: Deny
        priority: 4000
        direction: Inbound
      - name: ExternalTCP
        protocol: Tcp
        destination_port_range:
          - 22
          - 443
          - 830  # NETCONF over SSH
          - 8443
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1001
        direction: Inbound
      - name: InternalTCP
        protocol: Tcp
        destination_port_range: 23456-24156
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1002
        direction: Inbound
      - name: InternalUDP
        protocol: Udp
        destination_port_range: 12346-13046
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1003
        direction: Inbound
      - name: ICMP
        protocol: Icmp
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1004
    tags:
      Name: "{{ az_network_security_group }}"
      Creator: "{{ az_tag_creator }}"
      Organization: "{{ organization_name }}"

- name: "Block Outbound traffic: {{ az_network_security_group }}"
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_network_security_group }}"
    rules:
      - name: DenyAll
        access: Deny
        direction: Outbound
        priority: 4000
      - name: ExternalTCP-out
        protocol: Tcp
        destination_port_range:
          - 22
          - 443
          - 830  # NETCONF over SSH
          - 8443
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1001
        direction: Outbound
      - name: InternalTCP-out
        protocol: Tcp
        destination_port_range: 23456-24156
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1002
        direction: Outbound
      - name: InternalUDP-out
        protocol: Udp
        destination_port_range: 12346-13046
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1003
        direction: Outbound
      - name: ICMP-out
        protocol: Icmp
        source_address_prefix: "{{ az_allowed_subnets }}"
        access: Allow
        priority: 1004
        direction: Outbound
    tags:
      Name: "{{ az_network_security_group }}"
      Creator: "{{ az_tag_creator }}"
      Organization: "{{ organization_name }}"
  when: az_nsg_block_edgess
