# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

organization_name: null  # has to be set by user


# Deployment results path
results_dir: "{{ playbook_dir }}/results"

# Path to templated userdata config
userdata_manager_path: "{{ results_dir }}/.userdata_manager"
userdata_vbond_path: "{{ results_dir }}/.userdata_vbond"
userdata_vsmart_path: "{{ results_dir }}/.userdata_vsmart"


##########################################
#     SD-WAN Instances configuration     #
##########################################

# Cloud-init general configurations
admin_username: admin
admin_password: example_password  # pragma: allowlist secret
vbond_port: 12346
default_vbond_ip: 192.168.1.199  # default ips from official Cisco guides
vbond_transport_private_ip: null
vbond_transport_public_ip: null

###############################
#          Controllers        #
###############################

# Manager
site_id_manager: 100
manager_instances: []

# vBond
site_id_vbond: 200
vbond_instances: []


# vSmart
site_id_vsmart: 300
vsmart_instances: []

# cedge C8000K
edge_instances: []
