# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

# For Validator
#
# 2 aws_network_interface
# 2 aws_network_interface_attachment
# 2 aws_eip
# 1 ec2 instance


# NICs
- name: Filter required subnets for instance creation. Set aws_mgmt_subnet and aws_transport_subnet facts
  ansible.builtin.set_fact:
    aws_mgmt_subnet: "{{ aws_subnets_config | selectattr('tags.VPN', 'equalto', '512') | list | first }}"
    aws_transport_subnet: "{{ aws_subnets_config | selectattr('tags.VPN', 'equalto', '0') | list | first }}"

- name: Create network interfaces for Validator
  amazon.aws.ec2_eni:
    subnet_id: "{{ subnet_item.id }}"
    description: Network interface for SD-WAN Controller
    security_groups: "{{ aws_security_group_config.group_id }}"
    region: "{{ aws_region }}"
    tags:
      Name: "nic-{{ subnet_item.tags.Name }}"
      Creator: "{{ aws_tag_creator }}"
      Machine: "{{ hostname }}"
      VPN: "{{ subnet_item.tags.VPN }}"
  register: network_interfaces_validator
  loop: "{{ [aws_mgmt_subnet, aws_transport_subnet] }}"
  loop_control:
    loop_var: subnet_item
    label: "nic-{{ subnet_item.tags.Name }}"

- name: Set aws_network_interfaces fact with a list of interfaces for Validator
  ansible.builtin.set_fact:
    aws_network_interfaces: "{{ network_interfaces_validator.results | map(attribute='interface') | list }}"

- name: Filter aws_network_interfaces for instance creation. Set aws_mgmt_nic and aws_transport_nic facts
  ansible.builtin.set_fact:
    aws_mgmt_nic: "{{ aws_network_interfaces | selectattr('tags.VPN', 'equalto', '512') | list | first }}"
    aws_transport_nic: "{{ aws_network_interfaces | selectattr('tags.VPN', 'equalto', '0') | list | first }}"


# EIPs
- name: Associate EIP with network interfaces
  amazon.aws.ec2_eip:
    device_id: "{{ interface_item.id }}"
    region: "{{ aws_region }}"
    in_vpc: true
    state: present
    reuse_existing_ip_allowed: true
    tags:
      Name: "eip-for-{{ interface_item.tags.Name }}"
      Creator: "{{ aws_tag_creator }}"
      Machine: "{{ hostname }}"
      VPN: "{{ interface_item.tags.VPN }}"
  loop: "{{ [aws_mgmt_nic, aws_transport_nic] }}"  # We do loop starting with mgmt nic, so we know results[0] is mgmt ip
  loop_control:
    loop_var: interface_item
    label: "eip-for-{{ interface_item.tags.Name }}"
  register: eip_validator
  retries: 3
  delay: 3
  until: eip_validator is succeeded

# validator_mgmt_private_ip
- name: Set validator_mgmt_private_ip fact
  ansible.builtin.set_fact:
    validator_mgmt_private_ip: "{{ aws_mgmt_nic.private_ip_address }}"
    validator_transport_private_ip: "{{ aws_transport_nic.private_ip_address }}"
    validator_mgmt_public_ip: "{{ eip_validator.results[0].public_ip }}"
    validator_transport_public_ip: "{{ eip_validator.results[1].public_ip }}"


# template cloud init with proper ip assigned to EiP
# cloud-init
- name: Set path for bootstrap configuration
  ansible.builtin.set_fact:
    generated_userdata_validator: "{{ userdata_validator_path }}-{{ hostname }}"
  changed_when: true

- name: Template userdata file for Validator
  ansible.builtin.template:
    src: ./userdata_validator.j2
    dest: "{{ generated_userdata_validator }}"
    mode: "0644"


# Validator
- name: Launch Validator
  amazon.aws.ec2_instance:
    count: 1
    instance_type: "{{ aws_validator_instance_type }}"
    image:
      id: "{{ aws_validator_ami_id }}"
    state: present
    vpc_subnet_id: "{{ aws_mgmt_subnet.id }}"
    region: "{{ aws_region }}"
    key_name: "{{ aws_key_name | default('') | bool | ternary(aws_key_name, omit) }}"
    network:
      assign_public_ip: false
      interfaces:
        - id: "{{ aws_mgmt_nic.id }}"
          device_index: 0
          description: "{{ aws_mgmt_nic.tags.Name }}"
        - id: "{{ aws_transport_nic.id }}"
          device_index: 1
          description: "{{ aws_transport_nic.tags.Name }}"
    name: "{{ hostname }}"
    tags:
      Name: "{{ hostname }}"
      Creator: "{{ aws_tag_creator }}"
    user_data: "{{ lookup('file', generated_userdata_validator) }}"
    volumes:
      - device_name: /dev/xvda
        ebs:
          volume_size: 23
          delete_on_termination: true
  register: ec2_validator

- name: Store Validator instance details for deployment_results
  ansible.builtin.set_fact:
    instance:
      hostname: "{{ hostname }}"
      system_ip: "{{ system_ip }}"
      admin_username: "{{ admin_username }}"
      admin_password: "{{ admin_password }}"
      mgmt_public_ip: "{{ eip_validator.results[0].public_ip }}"
      transport_public_ip: "{{ eip_validator.results[1].public_ip }}"
  changed_when: true
  notify: Show deployment_facts
  register: _validator_facts
  retries: 3
  delay: 5
  until: _validator_facts is succeeded

- name: Update deployment facts - Validator - that will be consumed by Manager-client in Ansible
  ansible.builtin.set_fact:
    deployment_facts:
      validator_instances: "{{ deployment_facts.validator_instances + [instance] }}"
      manager_instances: "{{ deployment_facts.manager_instances }}"
      controller_instances: "{{ deployment_facts.controller_instances }}"

- name: Copy resources information to log file
  ansible.builtin.blockinfile:
    create: true
    state: present
    mode: "0644"
    insertafter: EOF
    dest: "{{ aws_deployed_controllers_data }}"
    marker: "\n--------------    ec2 Validator   --------------\n"
    content: "{{ ec2_validator | to_nice_yaml }}"

- name: Allow traffic outside VPC for Validator IP addresses
  amazon.aws.ec2_security_group:
    name: "{{ aws_security_group_config.group_name }}"
    description: "Security Group for SD-WAN instances"
    vpc_id: "{{ aws_vpc_config.id }}"
    region: "{{ aws_region }}"
    purge_rules: false
    purge_tags: false
    purge_rules_egress: false
    rules:
      - proto: all
        cidr_ip: "{{ eip_validator.results[0].public_ip }}/32"
        rule_desc: "{{ hostname }} - mgmt (VPN 512)"
      - proto: all
        cidr_ip: "{{ eip_validator.results[1].public_ip }}/32"
        rule_desc: "{{ hostname }} - transport (VPN 0)"
    rules_egress: []
  register: allow_traffic
  retries: 3
  delay: 3
  until: allow_traffic is succeeded
