# Copyright 2024 Cisco Systems, Inc. and its affiliates
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

---

# VPN subnets from which we can connect to AWS EIPs (Security Group config)
aws_allowed_subnets: null

#####################################
#     General AWS configuration     #
#####################################

organization_name: null  # has to be set by user


# Common
aws_region: null
aws_resources_prefix: "{{ organization_name }}"
aws_tag_creator: "{{ organization_name }}"
all_aws_regions: "{{ [aws_region] + wan_edges | default([]) | json_query('[?aws_region].aws_region') | unique }}"

# VPC
aws_vpc_name: "{{ aws_resources_prefix }}-vpc"
aws_vpc_cidr: 10.0.0.0/16  # default ips from official Cisco guides

# IGW
aws_igw_name: "{{ aws_resources_prefix }}-igw"

# SUBNETs
aws_subnets: |
  {% filter from_yaml %}
  - name: "{{ aws_resources_prefix }}-mgmt-subnet-512"
    subnet_cidr: "10.0.1.0/24"  # default ips from official Cisco guides
    VPN: 512
    type: mgmt
  - name: "{{ aws_resources_prefix }}-transport-subnet-0"
    subnet_cidr: "10.0.2.0/24"  # default ips from official Cisco guides
    VPN: 0
    type: transport
  {% if vmanage_instances is defined and vmanage_instances | length > 2 %}
  - name: "{{ aws_resources_prefix }}-cluster-subnet-0"
    subnet_cidr: "10.0.3.0/24"
    VPN: 0
    type: cluster
  {% endif %}
  {% if ux20_deployment is defined and ux20_deployment == true %}
  - name: "{{ aws_resources_prefix }}-service-subnet-10"
    subnet_cidr: "10.0.4.0/24"  # default ips from official Cisco guides
    VPN: 10
    type: service
  {% endif %}
  {% endfilter %}

# ROUTE TABLEs
aws_route_table_name: "{{ aws_resources_prefix }}-rtab"

# SECURITY GROUPs
aws_security_group_name: "{{ aws_resources_prefix }}-sg"
aws_vpn_name: "{{ aws_resources_prefix }}-vpn"
aws_eip_name: "{{ aws_resources_prefix }}-eip"
aws_nacl_name: "{{ aws_resources_prefix }}-nacl"
