---

#######################################
#     Required configuration data     #
#######################################

organization_name: null

# aws_allowed_subnets is list of subnets, that are allowed to access your instances via security group in AWS
# See https://docs.aws.amazon.com/vpc/latest/userguide/security-group-rules.html to learn more
#
# example configuration is:
# aws_allowed_subnets:
#   - 15.15.0.0/16
#   - 10.10.0.0/16
aws_allowed_subnets: null

#####################################
#     General AWS configuration     #
#####################################

# Common
aws_region: us-east-1
aws_resources_prefix: "{{ organization_name }}"
aws_tag_creator: "{{ organization_name }}"
aws_availibility_zone: us-east-1a  # we cannot use us-east-1e for c5.9xlarge, therefore we use us-east-1a

# VPC
aws_vpc_name: "{{ aws_resources_prefix }}-vpc"
aws_vpc_cidr: 10.0.0.0/16  # default ips from official Cisco guides

# IGW
aws_igw_name: "{{ aws_resources_prefix }}-igw"

# SUBNETs
aws_subnets: |
  {% filter from_yaml %}
  - name: "{{ aws_resources_prefix }}-mgmt-subnet-512"
    subnet_cidr: "10.0.1.0/24"  # default ips from official Cisco guides
    VPN: 512
    type: mgmt
  - name: "{{ aws_resources_prefix }}-transport-subnet-0"
    subnet_cidr: "10.0.2.0/24"  # default ips from official Cisco guides
    VPN: 0
    type: transport
  {% if manager_instances is defined and manager_instances | length > 2 %}
  - name: "{{ aws_resources_prefix }}-cluster-subnet-0"
    subnet_cidr: "10.0.3.0/24"
    VPN: 0
    type: cluster
  {% endif %}
  {% if ux20_deployment is defined and ux20_deployment == true %}
  - name: "{{ aws_resources_prefix }}-service-subnet-10"
    subnet_cidr: "10.0.4.0/24"  # default ips from official Cisco guides
    VPN: 10
    type: service
  {% endif %}
  {% endfilter %}

# ROUTE TABLEs
aws_route_table_name: "{{ aws_resources_prefix }}-rtab"

# SECURITY GROUPs
aws_security_group_name: "{{ aws_resources_prefix }}-sg"
aws_vpn_name: "{{ aws_resources_prefix }}-vpn"
aws_eip_name: "{{ aws_resources_prefix }}-eip"
aws_nacl_name: "{{ aws_resources_prefix }}-nacl"


##########################################
#     SD-WAN Instances configuration     #
##########################################

# Cloud-init general configurations
admin_username: admin
admin_password: null  # pragma: allowlist secret
vbond_port: 12346
# vbond_transport_private_ip: null   # note that default: 192.168.1.199
# vbond_transport_public_ip: null    # note that default: 192.168.1.199



###############################
#          Controllers        #
###############################

# Manager
aws_manager_ami_id: null
aws_manager_instance_type: "c5.9xlarge"

site_id_manager: 100

manager_instances:
  - hostname: "{{ aws_resources_prefix }}-Manager"
    system_ip: 192.168.1.1
    site_id: "{{ site_id_manager }}"


# vBond
aws_vbond_ami_id: null
aws_vbond_instance_type: "c5.large"

site_id_vbond: 200

vbond_instances:
  - hostname: "{{ aws_resources_prefix }}-vBond"
    system_ip: 192.168.3.1
    site_id: "{{ site_id_vbond }}"


# vSmart
aws_vsmart_ami_id: null
aws_vsmart_instance_type: "c5.large"

site_id_vsmart: 300

vsmart_instances:
  - hostname: "{{ aws_resources_prefix }}-vSmart"
    system_ip: 192.168.2.1
    site_id: "{{ site_id_vsmart }}"





################################
#          Edge devices        #
################################

# cedge C8000K
aws_cedge_ami_id: null
# try this one also: ami-09db869a0fe05bd4e
aws_cedge_instance_type: "c5.large"


##########################################
#       Reusable deployment facts        #
##########################################

results_dir: "{{ playbook_dir }}/results"

# If user do not provide "results_path_controllers" and "results_path_edges" variable, they will be automatically generated
# with timestamp (which is recommended usage)
# See `roles/aws_controllers/tasks/generate_deployment_facts.yml` and `roles/aws_edges/tasks/generate_deployment_facts.yml` for more information

# results_path_controllers: "{{ results_dir }}/deployment_facts_controllers.yml"
# results_path_edges: "{{ results_dir }}/deployment_facts_edges.yml"
