---

######################################
#       Generated files paths        #
######################################

results_dir: "{{ playbook_dir }}/results"


#######################################
#     Required configuration data     #
#######################################

organization_name: dummyorg
resources_prefix: "{{ organization_name }}"

cloud_provider: null  # can be either aws or azure

# Cloud-init general configurations
admin_username: admin
admin_password: dummypassword  # pragma: allowlist secret
vbond_port: 12346
vbond_transport_private_ip: X.X.X.X
vbond_transport_public_ip: Y.Y.Y.Y


###############################
#          Controllers        #
###############################

# Manager
site_id_manager: 100

manager_instances:
  - hostname: terraformmanager1 # "{{ resources_prefix }}-Manager"
    system_ip: 192.168.1.1
    site_id: "{{ site_id_manager }}"
    vpn0_default_gateway: 10.0.2.1  # has to be set if cloud_provider == "azure"

# vBond
site_id_vbond: 200

vbond_instances:
  - hostname: terraformvbond1 # "{{ resources_prefix }}-vBond"
    system_ip: 192.168.3.1
    site_id: "{{ site_id_vbond }}"
    vpn0_default_gateway: 10.0.2.1  # has to be set if cloud_provider == "azure"


# vSmart
site_id_vsmart: 300

vsmart_instances:
  - hostname: terraformvsmart1 # "{{ resources_prefix }}-vSmart"
    system_ip: 192.168.2.1
    site_id: "{{ site_id_vsmart }}"
    vpn0_default_gateway: 10.0.2.1  # has to be set if cloud_provider == "azure"



################################
#          Edge devices        #
################################

edge_instances:
  - hostname: terraformcedge1
    otp: XXX
    site_id: 1002
    system_ip: 192.168.102.1
    uuid: XXXX-XXXX-XXXX
    vbond: 1.1.1.1
