# .github/workflows/ansible-lint.yml
name: Ansible Lint

on:
  pull_request:

  push:
    branches:
      - main

permissions: read-all

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        shell: sh


    steps:
      - name: Check out the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.10'

      - name: Run check-yaml, end-of-file-fixer, trailing-whitespace
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.8.1

      - name: Install detect-secrets
        run: pip install detect-secrets==1.4.0

      - name: Run detect-secrets
        run: detect-secrets scan
