# .github/workflows/ansible-lint.yml
name: Ansible Lint

on:
  pull_request:

  push:
    branches:
      - main

permissions: read-all

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14']
    defaults:
      run:
        shell: sh


    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: Run check-yaml, end-of-file-fixer, trailing-whitespace
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

      - name: Run ansible-lint
        uses: ansible/ansible-lint@665d9e07a1943254d2910faffc106adaf7ea7294 # v26.8.0

      - name: Install detect-secrets
        run: pip install detect-secrets==1.5.0

      - name: Run detect-secrets
        run: detect-secrets scan
